
trigger:
- master

pool:
  ubuntu
  

stages:
  - stage: Build
    jobs:
    - job: job1
      steps:
      - bash: echo "New line added"
  - stage: QA
    dependsOn: Build
    jobs:   
    - job: job2
      steps:
        - bash: echo "2nd line added"
  - stage: Dev
    dependsOn: Build
    jobs:   
    - job: job3
      steps:
        - bash: echo "3rd line added"



