
trigger:
- master

pool:
  myagent
  

stages:
  - stage: Build
    jobs:
    - job: 
      steps:
      - bash: echo "New line added"
  - task: CopyPublishBuildArtifacts@1
    inputs:
      CopyRoot: '$(Agent.BuildDirectory)'
      ArtifactName: 'newart'
      ArtifactType: 'FilePath'


