
trigger:
- master

pool:
  myagent
  

stages:
  - stage: Build
    jobs:
    - job: job1
      steps:
      - powershell: echo "New line added"
  - stage: QA
    jobs:   
    - job: job2
      steps:
        - powershell: echo "2nd line added"



